spring.application.name=auth-service-api

server.port=9092



#database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/cpd_hotel_auth?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
#java wants to connect the mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



#In system,we have to tell use the mysql version
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.generate-ddl=true
# when we do changes in database it will update in the code also
spring.jpa.hibernate.ddl-auto=update



#===keycloack config
spring.security.oauth2.resourceserver.jwt.token-uri=http://localhost:8080/realms/cpd/protocol/openid-connect/token
spring-security.oauth2.resourceserver.jwt.issuer.uri=http://localhost:8080/realms/cpd
public.key.string=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1lwrOdGnGeM3kAPhxgjYOaJtHyUyiZlAdgmR1804Y845mRGUlzGbjS0k4ukUENiE3eF5Z38doTIdHpGWVTUjb8+mfF4qM4M2LTXSVhidEnhtK7RRQFzfat8tEKBCbSwk4ORyo2CI//dEPwLCT1TT8G95E4fC5EjD6H7DPgaeu5d5EYtUSHCp2oXYc2edCUrEfaNAGdxFfpjlx52QAcOzE0gOEnMuDlX1E5mESAJTrDxsgi0BLrZBjNOhbVak8AyUb+GYFN2PcqSQJcGnwrEug9MlMRsA+JODID7wdRW6RKfBhFUXUS5tUChKusyOrfxlZpkcvSTUHbZLiWLw07wxAQIDAQAB

keycloack.config.realm=cpd
keycloack.config.server-url=http://localhost:8080/
keycloack.config.client-id=cpd-client
keycloack.config.grand-type=password
keycloack.config.name=thirusudan110@gmail
keycloack.config.secret=6M869fNzjTQmnC38XqyQP28r9GPXmLkS
keycloack.config.password=1234

emailKey=SG.iJRXu3F0QWeIT4_PEIzJ7g.LomU5nqShppepqJ3DQJvm3vOGyH9AZ0nyHI_rFmIto
  #Q

fromEmail=thirusudan110@gmail.com
ReplyEmail=thirusudan110@gmail.com

accessKey=qqdwijwdij
secret=wjdlsjasak
bucketName=test-bucket-name
region=ap-south-1

